import { DEFAULT_AGENT_KIND, isAgentKind, type AgentKind } from '../../../shared/agent-kind'

interface AgentProfile {
  readonly kind: AgentKind
  readonly persistResponseBoundaries: boolean
  readonly instructions?: string
  readonly key?: string
}

const PROFILES: Readonly<Record<AgentKind, AgentProfile>> = {
  code: Object.freeze({ kind: 'code', persistResponseBoundaries: false }),
  work: Object.freeze({
    kind: 'work',
    persistResponseBoundaries: true,
    key: 'work:2',
    instructions: [
      'Help the user complete practical work: documents, research, organization, and analysis.',
      'Clarify the purpose, expected deliverable, and source materials only when needed to proceed.',
      'For multi-step work, use the existing task tools to track progress; do not create tasks for every simple answer.',
      'Use the available file, search, shell, and extension tools and check the actual results.',
      'Write final ordinary deliverables directly to /tmp/<filename> (the native absolute output directory provided below). Keep intermediate scripts and working files in a subdirectory or the working directory, then move only the checked final deliverables to the output root.',
      "Use a distinct filename for each task in this shared output directory; do not overwrite another task's output.",
      'Composer attachments in /tmp are input sources. Keep their original files intact and write requested revisions or summaries as distinct final output files.',
      'Successful Write/Edit operations in the output root are collected automatically. For files generated by shell commands, such as presentations, include an explicit Markdown link to each finished output file in the final response so Orca can collect it. Do not link intermediate files as deliverables.',
      'Ordinary generated documents are file outputs. Artifacts are a separate publication-oriented result: use the artifact publisher only when the user requests an artifact or a result intended for publishing or sharing. This does not upload it to an external service.',
      'Explain the result, file locations, and anything that remains incomplete. Existing workspace and permission rules still apply.'
    ].join('\n')
  })
}

export function resolveAgentProfile(kind: AgentKind): AgentProfile {
  return PROFILES[kind]
}

// The caller supplies the authoritative DB/lease birth value. Only a new birth defaults.
export function resolveAgentKind(
  requested: unknown,
  inherited: unknown
): { ok: true; kind: AgentKind } | { ok: false; reason: 'invalid' | 'mismatch' } {
  if (requested !== undefined && !isAgentKind(requested)) return { ok: false, reason: 'invalid' }
  if (inherited !== undefined && !isAgentKind(inherited)) return { ok: false, reason: 'invalid' }
  if (requested !== undefined && inherited !== undefined && requested !== inherited)
    return { ok: false, reason: 'mismatch' }
  return { ok: true, kind: inherited ?? requested ?? DEFAULT_AGENT_KIND }
}
